/* Generates theme.css (Tailwind v4) from colors.js. Run: node build-theme.cjs */
const fs = require('fs');
const path = require('path');
const { colors, radius, shadow, font, ease, duration } = require('./colors.js');

const lines = [];
for (const [k, v] of Object.entries(colors)) lines.push(`  --color-${k}: var(${v});`);
for (const [k, v] of Object.entries(radius)) lines.push(`  --radius-${k}: var(--vhyx-radius-${v});`);
for (const [k, v] of Object.entries(shadow)) lines.push(`  --shadow-${k}: var(--vhyx-shadow-${v});`);
for (const [k, v] of Object.entries(font)) lines.push(`  --font-${k}: var(--vhyx-font-${v});`);
for (const [k, v] of Object.entries(ease)) lines.push(`  --ease-${k}: var(--vhyx-easing-${v});`);
for (const [k, v] of Object.entries(duration)) lines.push(`  --duration-${k}: var(--vhyx-duration-${v});`);

const css = `/* AUTO-GENERATED by build-theme.cjs — do not edit.
 * @vhyxui/tailwind — Tailwind CSS v4 theme.
 *
 *   @import "tailwindcss";
 *   @import "@vhyxui/tailwind/theme.css";
 *   @import "@vhyxui/tokens/tokens.css";
 *   @import "@vhyxui/react/style.css";
 *
 * \`inline\` keeps the var() references, so utilities follow the active theme.
 */
@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *));

@theme inline {
${lines.join('\n')}
}
`;
fs.writeFileSync(path.join(__dirname, 'theme.css'), css);
console.log('theme.css written');
