// Icon pipeline. Sources of truth (all original Vhyxara drawings): icons/*.svg (+ optional .16.svg optical and .solid.svg variants)
// and icons/icons.json. `node scripts/build.mjs` regenerates src/generated/*;
// `node scripts/build.mjs --assets` writes dist/sprite.svg, dist/icons.json and dist/style.css.
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { componentName, loadIcons, nodeName, toSprite } from './lib.mjs';

const root = new URL('../', import.meta.url);
const icons = loadIcons(new URL('icons/', root).pathname);
const HEADER = '// Generated by scripts/build.mjs from icons/*.svg. Do not edit by hand.\n';
const foreign = icons.filter((i) => i.source !== 'vhyxara').map((i) => i.name);
if (foreign.length) throw new Error(`Only original Vhyxara drawings are allowed (source "vhyxara"): ${foreign.join(', ')}`);

if (process.argv.includes('--assets')) {
  const dist = new URL('dist/', root);
  mkdirSync(dist, { recursive: true });
  writeFileSync(new URL('sprite.svg', dist), toSprite(icons));
  const meta = icons.map((i) => ({
    name: i.name,
    component: componentName(i.name),
    category: i.category,
    tags: i.tags,
    variants: ['outline', ...(i.solid ? ['solid'] : []), ...(i.small ? ['16px'] : [])],
    source: i.source,
  }));
  writeFileSync(new URL('icons.json', dist), JSON.stringify(meta, null, 2) + '\n');
  copyFileSync(new URL('src/style.css', root), new URL('style.css', dist));
  console.log(`Wrote sprite.svg, icons.json and style.css for ${icons.length} icons`);
} else {
  const gen = new URL('src/generated/', root);
  mkdirSync(gen, { recursive: true });
  const nodeLines = [HEADER + "import type { IconNode } from '../types.js';\n"];
  const reactLines = [HEADER + "import { createIcon } from '../createIcon.js';", `import { ${icons.flatMap((i) => [nodeName(i.name), ...(i.small ? [nodeName(i.name, 'small')] : []), ...(i.solid ? [nodeName(i.name, 'solid')] : [])]).join(', ')} } from './nodes.js';\n`];
  const registry = [HEADER + `import { ${icons.map((i) => nodeName(i.name)).join(', ')} } from './nodes.js';\n`, '/** Every icon drawing by name — used by the web component and gallery. Not tree-shakeable. */', 'export const icons = {'];
  for (const i of icons) {
    nodeLines.push(`/** ${i.name} — ${i.category}${i.tags.length ? `; ${i.tags.slice(0, 6).join(', ')}` : ''} */`);
    nodeLines.push(`export const ${nodeName(i.name)}: IconNode = ${JSON.stringify(i.main.nodes)};`);
    if (i.small) nodeLines.push(`export const ${nodeName(i.name, 'small')}: IconNode = ${JSON.stringify(i.small.nodes)};`);
    if (i.solid) nodeLines.push(`export const ${nodeName(i.name, 'solid')}: IconNode = ${JSON.stringify(i.solid.nodes)};`);
    const opts = i.small ? `, { small: ${nodeName(i.name, 'small')} }` : '';
    reactLines.push(`export const ${componentName(i.name)} = /*#__PURE__*/ createIcon('${componentName(i.name)}', ${nodeName(i.name)}${opts});`);
    if (i.solid) reactLines.push(`export const ${componentName(i.name, 'solid')} = /*#__PURE__*/ createIcon('${componentName(i.name, 'solid')}', ${nodeName(i.name, 'solid')}, { solid: true });`);
    registry.push(`  '${i.name}': ${nodeName(i.name)},`);
  }
  registry.push('} as const;', '', '/** Name of any icon in the set, e.g. "triangle-alert". */', 'export type IconName = keyof typeof icons;', '', '/** All icon names, sorted. */', 'export const iconNames = Object.keys(icons) as IconName[];');
  writeFileSync(new URL('nodes.ts', gen), nodeLines.join('\n') + '\n');
  writeFileSync(new URL('react.ts', gen), reactLines.join('\n') + '\n');
  writeFileSync(new URL('registry.ts', gen), registry.join('\n') + '\n');
  console.log(`Generated ${icons.length} icons`);
}
