// Generates src/icons.ts from Lucide's icon-node data (ISC, see NOTICE).
// Run with `pnpm --filter @vhyxui/icons generate` after changing ICONS.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const nodes = JSON.parse(readFileSync(require.resolve('lucide-static/icon-nodes.json'), 'utf8'));

// Source icon name → exported component name (without the Icon suffix).
const ICONS = {
  // status
  check: 'Check', x: 'X', info: 'Info', 'triangle-alert': 'TriangleAlert',
  'circle-check': 'CircleCheck', 'circle-x': 'CircleX', 'circle-alert': 'CircleAlert', 'loader-circle': 'LoaderCircle',
  // navigation and actions
  menu: 'Menu', search: 'Search', copy: 'Copy', plus: 'Plus', minus: 'Minus', trash: 'Trash',
  'arrow-right': 'ArrowRight', 'arrow-up': 'ArrowUp', 'arrow-down': 'ArrowDown', 'arrow-up-down': 'ArrowUpDown', 'trending-up': 'TrendingUp', 'trending-down': 'TrendingDown', 'external-link': 'ExternalLink', 'chevron-down': 'ChevronDown', 'chevron-right': 'ChevronRight', 'chevron-left': 'ChevronLeft', 'chevron-up': 'ChevronUp',
  settings: 'Settings', mail: 'Mail', inbox: 'Inbox', star: 'Star', 'face-slightly-smiling': 'Smile',
  // theme
  sun: 'Sun', moon: 'Moon',
  // media
  play: 'Play', pause: 'Pause', 'skip-back': 'SkipBack', 'circle-play': 'CirclePlay', 'image-play': 'ImagePlay',
  // product and feature
  accessibility: 'Accessibility', activity: 'Activity', blocks: 'Blocks', bot: 'Bot', brush: 'Brush', bug: 'Bug',
  code: 'Code', coins: 'Coins', 'eye-off': 'EyeOff', feather: 'Feather', 'git-branch': 'GitBranch', laptop: 'Laptop',
  layers: 'Layers', 'life-buoy': 'LifeBuoy', lock: 'Lock', package: 'Package', palette: 'Palette', 'pen-line': 'PenLine',
  puzzle: 'Puzzle', rocket: 'Rocket', 'shield-check': 'ShieldCheck', sparkles: 'Sparkles', stethoscope: 'Stethoscope',
  ticket: 'Ticket', 'waves-horizontal': 'Waves', workflow: 'Workflow', zap: 'Zap',
};

const missing = Object.keys(ICONS).filter((k) => !nodes[k]);
if (missing.length) throw new Error(`Unknown source icons: ${missing.join(', ')}`);

const lines = [
  '// Generated by scripts/generate.mjs. Do not edit by hand.',
  '// Icon artwork derived from Lucide (ISC); see NOTICE.',
  "import { createIcon } from './createIcon.js';",
  '',
];
for (const [src, name] of Object.entries(ICONS).sort((a, b) => a[1].localeCompare(b[1]))) {
  const node = nodes[src].map(([tag, attrs]) => [tag, Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== 'key'))]);
  lines.push(`export const ${name}Icon = /*#__PURE__*/ createIcon('${name}Icon', ${JSON.stringify(node)});`);
}
writeFileSync(new URL('../src/icons.ts', import.meta.url), lines.join('\n') + '\n');
console.log(`Generated ${Object.keys(ICONS).length} icons`);
